<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Revit_All_Main_Versions_API_x64" Version="$(RevitVersion)" />
    <PackageVersion Include="Nice3point.BenchmarkDotNet.Revit" Version="$(MajorRevitVersion).1.0" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.9" />
  </ItemGroup>
</Project>
